tasks:
  - name: cert-manager-pkg-flavor
    description: "Publish pkg flavor of Cert-Manager"
    actions:
      - cmd: zarf package publish zarf-package-*.zst oci://ghcr.io/defenseunicorns/packages
