apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bootstrap-ca-cert
  namespace: cert-manager
spec:
  isCA: true
  commonName: bootstrap-ca-cert
  secretName: bootstrap-ca
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: bigbang-ca-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: bootstrap-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin-cert-test
  namespace: istio-system
spec:
  isCA: true
  commonName: bigbang-istio-gateway
  secretName: admin-cert-test
  secretTemplate:
    labels:
      app.kubernetes.io/istio-gateway-secret: admin
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: bigbang-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tenant-cert-test
  namespace: istio-system
spec:
  isCA: true
  commonName: bigbang-istio-gateway
  secretName: tenant-cert-test
  secretTemplate:
    labels:
      app.kubernetes.io/istio-gateway-secret: tenant
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: bigbang-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
