name: Publish Package

# Will remove before merge and make it only tags
on:
  workflow_call:
    inputs:
      working_dir:
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Free GH runner space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          df -h

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup


      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  create-package:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        flavor: [upstream, registry1]
    steps:
      - name: Create Package Flavors
        run: uds run create-pkg-flavor --set FLAVOR=${{ matrix.flavor }}

  publish-package:
    runs-on: ubuntu-latest
    needs: create-package
    strategy:
      matrix:
        flavor: [upstream, registry1]
    steps:
      - name: Publish Zarf Package Flavor
        run: uds run publish-pkg-flavor --set FLAVOR=${{ matrix.flavor }}

      - name: Publish Zarf Skeleton
        run: zarf package publish . oci://ghcr.io/defenseunicorns/packages
        working-directory: ${{ inputs.working_dir }}
        timeout-minutes: 60
